# Generated by Django 4.2.7 on 2023-12-04 12:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairs', '0002_alter_category_options_alter_material_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='discount',
            field=models.IntegerField(default=0, verbose_name='Скидка'),
        ),
        migrations.AddField(
            model_name='chair',
            name='price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена'),
            preserve_default=False,
        ),
    ]
