# Generated by Django 4.2.7 on 2023-12-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairs', '0003_chair_discount_chair_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='chair',
            name='discounted_price',
            field=models.DecimalField(decimal_places=2, default=1, max_digits=10, verbose_name='Цена со скидкой'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='chair',
            name='discount',
            field=models.IntegerField(blank=True, default=0, null=True, verbose_name='Скидка'),
        ),
    ]
