# Generated by Django 4.2.7 on 2023-12-04 12:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairs', '0004_chair_discounted_price_alter_chair_discount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chair',
            name='discounted_price',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Цена со скидкой'),
        ),
    ]
