# Generated by Django 4.2.7 on 2023-12-04 15:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chairs', '0006_alter_category_name'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chair',
            options={'ordering': ('-created',), 'verbose_name': 'Стул', 'verbose_name_plural': 'Стулья'},
        ),
        migrations.AddField(
            model_name='chair',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default='2023-12-04', verbose_name='Дата создания'),
            preserve_default=False,
        ),
    ]
